### ISSUE TITLE
Projekt alap

### ISSUE THREAD

**Issue by szalai111** [Teaching-projects/januari-beadando-szalai111#1]
Ez még csak a projekt alapja, ami még folytatva lesz meg még lesznek extrák hozzáadva, ennél leginkább az lenne a fontos, hogy jó-e így a lehetőség választás?
[projekt.zip](https://github.com/Teaching-projects/januari-beadando-szalai111/files/7809310/projekt.zip)

**Comment by hegyhati** [comment]
no, nem, nem igy, tessek a kodot feltenni rendesen, nem az issue-ba mellekelve.

**Comment by hegyhati** [comment]
Ez is egy 0 byte-os pythont tartalmazo zip

**Comment by szalai111** [comment]
@hegyhati, ez a történet része, még az érdekelne leginkább hogy az életerő rendszert mivel kéne megoldanom leginkább. Előre is köszönöm.

**Comment by hegyhati** [comment]
A `time.sleep(4)` igazabol itt szerintem nem azt csinalja, amit szeretne, hogy ha nem irsz, akkor szoljon, mert itt addig nem is tudsz irni, amig az a 4 sec le nem tellik. De igazabol ez mindegy.  De a time-ot csak egyszer importald az elejen

fuggveny nevbol neha hianyzik az e.

A valtozonevek kisse felrevezetoek. A `valasz` nem a valaszt tarolja, azt az `opciov` tarolja. Logikusabb lenne, ha a `valasz` tarolna a valaszt, azt pedig hogy megfelelo-e a valasz, azt egy `megfelelo_valasz` tarolna, ami mivel csak igaz/hamis lehet, nem string lenne, hanem bool.

A 3-as jelenetnel nem jo, hogy fixen 70-et ir ki, nem a tenyleges eleterot. (ami amugy most maradjon nyugodtan igy globalban)

45 eleterot irsz, hogy vesztettem, de 40-et vonsz le.

Az utolsonal nem teljesen ertem a while ciklust, mert cikluson belul nem valtozik az eletero sehol.

**Comment by szalai111** [comment]
Arra szeretnék rákérdezni ,hogy maga szerint miképp lehetne megoldani az életerő rendszert?

**Comment by szalai111** [comment]
@hegyhati Most már feltöltöttem egy végleges verziót, ahol mindent javítottam, és csináltam egy működő életerő rendszert random sebzéssel. Remélem ez a projekt már megfelelő. A projekt_vegleges néven van leadva.

**Comment by hegyhati** [comment]
Megneztem, ebbe az eletero dologba elegge belekavarodtal, nem nagyon latom igy ertelmet. De ertekelve, hogy aktivan foglalkoztal a dologgal, legyen 5.
